### ISSUE TITLE
Model demo error

### ISSUE THREAD

**Issue by tunglambk** [sled-group/world-to-words#1]
The demo on Huggingface is having trouble

```
Runtime error
��  | 377M/499M [00:09<00:02, 42.5MB/s]
Downloading model.safetensors:  80%|███████▉  | 398M/499M [00:09<00:02, 43.9MB/s]
Downloading model.safetensors:  84%|████████▍ | 419M/499M [00:09<00:01, 50.8MB/s]
Downloading model.safetensors:  90%|█████████ | 451M/499M [00:10<00:00, 62.8MB/s]
Downloading model.safetensors:  95%|█████████▍| 472M/499M [00:10<00:00, 58.2MB/s]
Downloading model.safetensors:  97%|█████████▋| 482M/499M [00:10<00:00, 58.1MB/s]
Downloading model.safetensors: 100%|██████████| 499M/499M [00:11<00:00, 57.1MB/s]
Downloading model.safetensors: 100%|██████████| 499M/499M [00:11<00:00, 44.8MB/s]
Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/home/user/app/app.py", line 15, in <module>
    model, img_transform, tokenizer, post_processor, plot_results = torch.hub.load('Jiayi-Pan/RefCloze_Pub', 'flickr_base_model', force_reload=True)
  File "/home/user/.local/lib/python3.10/site-packages/torch/hub.py", line 558, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/torch/hub.py", line 587, in _load_local
    model = entry(*args, **kwargs)
  File "/home/user/.cache/torch/hub/Jiayi-Pan_RefCloze_Pub_main/hubconf.py", line 20, in flickr_base_model
    model.load_state_dict(model_checkpoint['model'])
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MDETR:
	Unexpected key(s) in state_dict: "transformer.text_encoder.embeddings.position_ids". 
```

**Comment by Jiayi-Pan** [comment]
The latest transformer package introduced some breaking changes which led to the error.

It has been fixed now.
